## Business Problem
Swiggy processes millions of food-delivery journeys across hundreds of cities every month. Accurate Estimated Time of Arrival (ETA) at order placement and during delivery is core to the customer experience — it affects conversion, cancellations, ratings, and retention. Today’s ETA accuracy suffers from many sources of uncertainty: highly variable traffic patterns, weather events, restaurant preparation variability, rider behaviour and skill, order batching/multiple deliveries, and city-specific operational constraints. Inaccurate ETAs cause:
Reduced customer trust and lower repeat orders.
Increased cancellations and refund costs.


Higher support volume and operational interventions.


Sub-optimal rider allocation and increased rider idle or overtime costs.

## Problem Statement
Swiggy’s objective is to predict the delivery time (minutes) per order at the moment of order placement (and update it dynamically), with business-grade accuracy and uncertainty estimates so the platform can
 (a) show reliable ETAs to customers
 (b) optimize rider allocation.
Build a production-ready, scalable Machine Learning system that predicts per-order delivery time (in minutes) using real-time and historical features (order, rider, restaurant, geospatial, traffic, weather, and temporal signals). The system must produce:

## Problem Type: Regression

Why is it Regression?

Regression is used when the target variable is a continuous numerical value.

In this project, we are predicting the delivery time in minutes, which can take values such as:

22 minutes

35 minutes

48 minutes

60 minutes 

Since the output is a continuous number, this is a Regression problem, not a Classification problem

## 3.target variable

the target variable is dependent variable. in this data the target variable is time_taken

## 4.features

These are the input variables used to predict the delivery time.
| Feature Name         | Description                              |   |
| -------------------- | ---------------------------------------- | - |
| rider_id             | Unique ID of delivery partner            |   |
| age                  | Rider's age                              |   |
| ratings              | Customer rating of rider                 |   |
| vehicle_condition    | Vehicle condition (0,1,2)                |   |
| type_of_vehicle      | Motorcycle, Scooter, etc.                |   |
| type_of_order        | Snack, Meal, Drinks, Buffet              |   |
| multiple_deliveries  | Number of deliveries assigned            |   |
| pickup_time_minutes  | Restaurant preparation time              |   |
| restaurant_latitude  | Restaurant latitude                      |   |
| restaurant_longitude | Restaurant longitude                     |   |
| delivery_latitude    | Customer latitude                        |   |
| delivery_longitude   | Customer longitude                       |   |
| is_weekend           | Weekend or not                           |   |
| order_time_hour      | Hour of order                            |   |
| order_time_of_day    | Morning, Afternoon, Evening, Night       |   |
| weather              | Weather condition                        |   |
| traffic              | Traffic condition                        |   |
| festival             | Festival day or not                      |   |
| city_type            | Urban / Metropolitan                     |   |
| city_name            | City name                                |   |
| distance             | Distance between restaurant and customer |   |
| order_date           | Order date                               |   |
| order_day            | Day of month                             |   |
| order_month          | Month                                    |   |
| order_day_of_week    | Day of week                              |   |

In [15]:
import warnings
warnings.filterwarnings("ignore")

In [16]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv(r"C:\Users\ACS\Downloads\swiggy_demographic (1).csv")
df

,rider_id,age,ratings,restaurant_latitude,restaurant_longitude,delivery_latitude,delivery_longitude,order_date,weather,traffic,...,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,INDORES13DEL02,37.0,4.9,22.745049,75.892471,22.765049,75.912471,2022-03-19,sunny,high,...,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,BANGRES18DEL02,34.0,4.5,12.913041,77.683237,13.043041,77.813237,2022-03-25,stormy,jam,...,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,BANGRES19DEL01,23.0,4.4,12.914264,77.678400,12.924264,77.688400,2022-03-19,sandstorms,low,...,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,COIMBRES13DEL02,38.0,4.7,11.003669,76.976494,11.053669,77.026494,2022-04-05,sunny,medium,...,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,CHENRES12DEL01,32.0,4.6,12.972793,80.249982,13.012793,80.289982,2022-03-26,cloudy,high,...,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45497,JAPRES04DEL01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24,windy,high,...,32,JAP,24,3,thursday,0,10.0,11.0,morning,1.489846
45498,AGRRES16DEL01,21.0,4.6,NaN,NaN,NaN,NaN,2022-02-16,windy,jam,...,36,AGR,16,2,wednesday,0,15.0,19.0,evening,NaN
45499,CHENRES08DEL03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-03-11,cloudy,low,...,16,CHEN,11,3,friday,0,15.0,23.0,night,4.657195
45500,COIMBRES11DEL01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-03-07,cloudy,high,...,26,COIMB,7,3,monday,0,5.0,13.0,afternoon,6.232393
45501,RANCHIRES09DEL02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-03-02,fog,medium,...,36,RANCHI,2,3,wednesday,0,5.0,17.0,evening,12.074396

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   rider_id              45502 non-null  str
 1   age                   43648 non-null  float64
 2   ratings               43594 non-null  float64
 3   restaurant_latitude   41872 non-null  float64
 4   restaurant_longitude  41872 non-null  float64
 5   delivery_latitude     41872 non-null  float64
 6   delivery_longitude    41872 non-null  float64
 7   order_date            45502 non-null  str
 8   weather               44977 non-null  str
 9   traffic               44992 non-null  str
 10  vehicle_condition     45502 non-null  int64
 11  type_of_order         45502 non-null  str
 12  type_of_vehicle       45502 non-null  str
 13  multiple_deliveries   44509 non-null  float64
 14  festival              45274 non-null  str
 15  city_type             44304 non-null  str
 16  time_taken            45502 non-null  int64
 17  city_name             45502 non-null  str
 18  order_day             45502 non-null  int64
 19  order_month           45502 non-null  int64
 20  order_day_of_week     45502 non-null  str
 21  is_weekend            45502 non-null  int64
 22  pickup_time_minutes   43862 non-null  float64
 23  order_time_hour       43862 non-null  float64
 24  order_time_of_day     45502 non-null  str
 25  distance              41872 non-null  float64
dtypes: float64(10), int64(5), str(11)
memory usage: 12.5 MB

In [20]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,43648.0,29.555008,5.761482,20.000000,25.000000,30.000000,35.000000,39.000000
ratings,43594.0,4.635287,0.313827,2.500000,4.500000,4.700000,4.900000,5.000000
restaurant_latitude,41872.0,18.913696,5.467265,9.957144,12.986047,19.065838,22.751234,30.914057
restaurant_longitude,41872.0,76.921664,3.503107,72.768726,73.897902,76.618203,78.368855,88.433452
delivery_latitude,41872.0,18.977356,5.469056,9.967144,13.065996,19.124049,22.820040,31.054057
delivery_longitude,41872.0,76.985325,3.503260,72.778726,73.940327,76.662620,78.405467,88.563452
vehicle_condition,45502.0,1.019406,0.835229,0.000000,0.000000,1.000000,2.000000,3.000000
multiple_deliveries,44509.0,0.744928,0.572488,0.000000,0.000000,1.000000,1.000000,3.000000
time_taken,45502.0,26.297591,9.386419,10.000000,19.000000,26.000000,32.000000,54.000000
order_day,45502.0,13.811657,8.709540,1.000000,6.000000,13.000000,20.000000,31.000000
order_month,45502.0,2.980726,0.546031,2.000000,3.000000,3.000000,3.000000,4.000000
is_weekend,45502.0,0.274867,0.446452,0.000000,0.000000,0.000000,1.000000,1.000000
pickup_time_minutes,43862.0,9.989399,4.087516,5.000000,5.000000,10.000000,15.000000,15.000000
order_time_hour,43862.0,17.423966,4.817856,0.000000,15.000000,19.000000,21.000000,23.000000
distance,41872.0,9.719296,5.602890,1.465067,4.657655,9.193014,13.680920,20.969489

In [21]:
df.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [22]:
numerical=['age','ratings','vehicle_condition','multiple_deliveries','order_day','order_month','is_weekend',
           'pickup_time_minutes','order_time_hour','distance']

# Dropping irrelevant columns

In [23]:
df.columns

Index(['rider_id', 'age', 'ratings', 'restaurant_latitude',
       'restaurant_longitude', 'delivery_latitude', 'delivery_longitude',
       'order_date', 'weather', 'traffic', 'vehicle_condition',
       'type_of_order', 'type_of_vehicle', 'multiple_deliveries', 'festival',
       'city_type', 'time_taken', 'city_name', 'order_day', 'order_month',
       'order_day_of_week', 'is_weekend', 'pickup_time_minutes',
       'order_time_hour', 'order_time_of_day', 'distance'],
      dtype='str')

In [24]:
df = df.drop(columns=['rider_id', 'order_date', 'restaurant_latitude', 'restaurant_longitude', 'delivery_latitude', 'delivery_longitude'])

In [25]:
x=df.drop(columns=['time_taken'])
y=df['time_taken']

In [26]:
df.head()

,age,ratings,weather,traffic,vehicle_condition,type_of_order,type_of_vehicle,multiple_deliveries,festival,city_type,time_taken,city_name,order_day,order_month,order_day_of_week,is_weekend,pickup_time_minutes,order_time_hour,order_time_of_day,distance
0,37.0,4.9,sunny,high,2,snack,motorcycle,0.0,no,urban,24,INDO,19,3,saturday,1,15.0,11.0,morning,3.025149
1,34.0,4.5,stormy,jam,2,snack,scooter,1.0,no,metropolitian,33,BANG,25,3,friday,0,5.0,19.0,evening,20.183530
2,23.0,4.4,sandstorms,low,0,drinks,motorcycle,1.0,no,urban,26,BANG,19,3,saturday,1,15.0,8.0,morning,1.552758
3,38.0,4.7,sunny,medium,0,buffet,motorcycle,1.0,no,metropolitian,21,COIMB,5,4,tuesday,0,10.0,18.0,evening,7.790401
4,32.0,4.6,cloudy,high,1,snack,scooter,1.0,no,metropolitian,30,CHEN,26,3,saturday,1,15.0,13.0,afternoon,6.210138

## Step 2: Data Preprocessing
- Handle missing values.
- Encode categorical variables.
- Scale numerical features.
- Apply the Transformation if required.
- Feature Selection
- Split data into train/test sets.

In [27]:
# seperate numerical and categorical columns

In [28]:
import warnings
warnings.filterwarnings("ignore")

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 45502 entries, 0 to 45501
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  43648 non-null  float64
 1   ratings              43594 non-null  float64
 2   weather              44977 non-null  str
 3   traffic              44992 non-null  str
 4   vehicle_condition    45502 non-null  int64
 5   type_of_order        45502 non-null  str
 6   type_of_vehicle      45502 non-null  str
 7   multiple_deliveries  44509 non-null  float64
 8   festival             45274 non-null  str
 9   city_type            44304 non-null  str
 10  time_taken           45502 non-null  int64
 11  city_name            45502 non-null  str
 12  order_day            45502 non-null  int64
 13  order_month          45502 non-null  int64
 14  order_day_of_week    45502 non-null  str
 15  is_weekend           45502 non-null  int64
 16  pickup_time_minutes  43862 non-null  float64
 17  order_time_hour      43862 non-null  float64
 18  order_time_of_day    45502 non-null  str
 19  distance             41872 non-null  float64
dtypes: float64(6), int64(5), str(9)
memory usage: 9.3 MB

In [30]:
df.isnull().sum()

age                    1854
ratings                1908
weather                 525
traffic                 510
vehicle_condition         0
type_of_order             0
type_of_vehicle           0
multiple_deliveries     993
festival                228
city_type              1198
time_taken                0
city_name                 0
order_day                 0
order_month               0
order_day_of_week         0
is_weekend                0
pickup_time_minutes    1640
order_time_hour        1640
order_time_of_day         0
distance               3630
dtype: int64

In [31]:
# nominal
nominal=['weather','type_of_order','type_of_vehicle','festival','city_name','order_day_of_week','order_time_of_day']
nominal

['weather',
 'type_of_order',
 'type_of_vehicle',
 'festival',
 'city_name',
 'order_day_of_week',
 'order_time_of_day']

In [32]:
# ordinal
ordinal=['traffic','city_type']
ordinal

['traffic', 'city_type']

In [33]:
df['city_type'].unique()

<ArrowStringArray>
['urban', 'metropolitian', 'semi-urban', nan]
Length: 4, dtype: str

In [34]:
order=[["low","medium","high","jam"],['semi-urban','urban','metropolitian']]

In [35]:
# numerical
numerical=['age','ratings','vehicle_condition','multiple_deliveries','order_day','order_month','is_weekend',
           'pickup_time_minutes','order_time_hour','distance']
numerical

['age',
 'ratings',
 'vehicle_condition',
 'multiple_deliveries',
 'order_day',
 'order_month',
 'is_weekend',
 'pickup_time_minutes',
 'order_time_hour',
 'distance']

# Pipeline creation

In [97]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler

In [98]:
from sklearn.compose import ColumnTransformer

In [99]:
numerical_pipeline=Pipeline([("Numerical impution",SimpleImputer(strategy="median")),
                            ("Feature Scaling",StandardScaler())])
numerical_pipeline

Pipeline(steps=[('Numerical impution', SimpleImputer(strategy='median')),
                ('Feature Scaling', StandardScaler())])

In [100]:
nominal_pipeline=Pipeline([("nominal imputation",SimpleImputer(strategy="most_frequent")),
                          ("Encoding",OneHotEncoder())])
nominal_pipeline

Pipeline(steps=[('nominal imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding', OneHotEncoder())])

In [101]:
ordinal_pipeline=Pipeline([("Ordinal imputation",SimpleImputer(strategy="most_frequent")),
                          ("Encoding",OrdinalEncoder(categories=order))])
ordinal_pipeline

Pipeline(steps=[('Ordinal imputation', SimpleImputer(strategy='most_frequent')),
                ('Encoding',
                 OrdinalEncoder(categories=[['low', 'medium', 'high', 'jam'],
                                            ['semi-urban', 'urban',
                                             'metropolitian']]))])

In [102]:
Data_preprocessing = ColumnTransformer([
    ('Nominal transformation', nominal_pipeline, nominal),
    ("Ordinal transformation", ordinal_pipeline, ordinal),
    ('Numerical Transformation', numerical_pipeline, numerical)
])

Data_preprocessing

ColumnTransformer(transformers=[('Nominal transformation',
                                 Pipeline(steps=[('nominal imputation',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('Encoding',
                                                  OneHotEncoder())]),
                                 ['weather', 'type_of_order', 'type_of_vehicle',
                                  'festival', 'city_name', 'order_day_of_week',
                                  'order_time_of_day']),
                                ('Ordinal transformation',
                                 Pipeline(steps=[('Ordinal imputation',
                                                  SimpleImpute...
                                                                             ['semi-urban',
                                                                              'urban',
                                                                              'metropolitian']]))]),
                                 ['traffic', 'city_type']),
                                ('Numerical Transformation',
                                 Pipeline(steps=[('Numerical impution',
                                                  SimpleImputer(strategy='median')),
                                                 ('Feature Scaling',
                                                  StandardScaler())]),
                                 ['age', 'ratings', 'vehicle_condition',
                                  'multiple_deliveries', 'order_day',
                                  'order_month', 'is_weekend',
                                  'pickup_time_minutes', 'order_time_hour',
                                  'distance'])])

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

# model building

## linear regression

In [67]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score

In [68]:
lr=Pipeline([
    ('Data_preprocessing',Data_preprocessing),
    ('algorithm',LinearRegression())
])
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 36.94136258193891
root_mean_squared_error 6.07794065304515
R2 score 0.5845096813390458

# KNN

In [69]:
from sklearn.neighbors import KNeighborsRegressor

In [70]:
knn=Pipeline([
    ('Data_preprocessing',Data_preprocessing),
    ('algorithm',KNeighborsRegressor())
])
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 34.29343588616636
root_mean_squared_error 5.85605975773526
R2 score 0.6142916880037183

# Decision tree regressor

In [71]:
from sklearn.tree import DecisionTreeRegressor

In [72]:
dt=Pipeline([
    ('Data_preprocessing',Data_preprocessing),
    ('algorithm',DecisionTreeRegressor())
])
dt.fit(x_train,y_train)
y_pred=dt.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 31.91044940116471
root_mean_squared_error 5.648933474662692
R2 score 0.6410938345629293

# Suppor vector machine

In [73]:
from sklearn.svm import SVR

In [74]:
svm=Pipeline([
    ('Data_preprocessing',Data_preprocessing),
    ('algorithm',SVR())
])
svm.fit(x_train,y_train)
y_pred=svm.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 25.880548012840798
root_mean_squared_error 5.08729279802537
R2 score 0.7089139005870704

# Random Forest Regressor

In [75]:
from sklearn.ensemble import RandomForestRegressor

In [76]:
RandomForestRegressor()

RandomForestRegressor()

In [77]:
rf=Pipeline([
    ('Data_preprocessing',Data_preprocessing),
    ('algorithm',RandomForestRegressor(random_state=23))
])
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 16.95031744863202
root_mean_squared_error 4.117076322905858
R2 score 0.8093548178545068

# XGBOOST

In [78]:
from xgboost import XGBRegressor

In [79]:
xgb=Pipeline([
     ('Data_preprocessing',Data_preprocessing),
    ('algorithm',XGBRegressor())
])
xgb.fit(x_train,y_train)
y_pred=xgb.predict(x_test)
print("mean_squared_error",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error",root_mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

mean_squared_error 16.577817916870117
root_mean_squared_error 4.071586608886719
R2 score 0.8135444521903992

# kfold-cross validation

In [80]:
from sklearn.model_selection import KFold,cross_val_score

In [81]:
kfcv=KFold(n_splits=5,shuffle=True, random_state=23)

In [82]:
cross_val_score(estimator=xgb,
               X=x,
               y=y,
               scoring='r2',
               cv=kfcv,
               n_jobs=-1).mean()

np.float64(0.8088161230087281)

# Step 4: Hyperparameter Tuning

In [84]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'algorithm__n_estimators':[100,200,300],
    'algorithm__max_depth':[4,6,7,8],
    'algorithm__learning_rate':[0.05,0.1,0.01]
}

grid_xgb=GridSearchCV(
     estimator=xgb,
    param_grid=param_grid,
    cv=kfcv,
    scoring='r2',
    n_jobs=-1
)
grid_xgb.fit(x_train,y_train)
print("Best Parameters:", grid_xgb.best_params_)
print("Best CV Score:", grid_xgb.best_score_)

Best Parameters: {'algorithm__learning_rate': 0.05, 'algorithm__max_depth': 8, 'algorithm__n_estimators': 200}
Best CV Score: 0.8153942108154297

# Bayesan Optimizer

In [85]:
def Objective(trial):
    # creating  search space
    n_estimators=trial.suggest_int("n_estimators",100,150,200)
    learning_rate=trial.suggest_float("learning_rate",0.01,0.1)
    Algorithm__max_depth=trial.suggest_int("Algorithm__max_depth",6,8)
    Algorithm__subsample=trial.suggest_float("Algorithm__subsample",0.8,1.0)
    
    # Training
    xgb=XGBRegressor(n_estimators=n_estimators,learning_rate=learning_rate,max_depth=Algorithm__max_depth,subsample=Algorithm__subsample)

    trial_pipeline = Pipeline(steps=[
        ('Data Preprocessing', Data_preprocessing), 
        ('Algorithm', xgb)])
    
    #scoring
    score=cross_val_score(trial_pipeline,x,y,scoring="r2",cv=kfcv,n_jobs=-1).mean()
    return score

In [57]:
import optuna

In [58]:
study=optuna.create_study(direction="maximize")

[I 2026-07-20 11:22:22,284] A new study created in memory with name: no-name-a55c69fc-90a6-415d-b6ea-8241d25c8fa9

In [86]:
study.optimize(Objective,n_trials=10)

[I 2026-07-20 15:27:30,896] Trial 0 finished with value: 0.8078342795372009 and parameters: {'n_estimators': 100, 'learning_rate': 0.028372653256626322, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8601357654675267}. Best is trial 0 with value: 0.8078342795372009.
[I 2026-07-20 15:27:37,002] Trial 1 finished with value: 0.8162664890289306 and parameters: {'n_estimators': 100, 'learning_rate': 0.06339216425139962, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.9591015629014061}. Best is trial 1 with value: 0.8162664890289306.
[I 2026-07-20 15:27:43,822] Trial 2 finished with value: 0.8189159154891967 and parameters: {'n_estimators': 100, 'learning_rate': 0.0548451185284156, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8480763631814661}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:27:50,649] Trial 3 finished with value: 0.8181241273880004 and parameters: {'n_estimators': 100, 'learning_rate': 0.047474299667115534, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8926340229511234}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:27:56,864] Trial 4 finished with value: 0.7648922085762024 and parameters: {'n_estimators': 100, 'learning_rate': 0.019572420096918283, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.8272502507539727}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:28:03,651] Trial 5 finished with value: 0.8185291409492492 and parameters: {'n_estimators': 100, 'learning_rate': 0.049339051089370714, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8384292089372809}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:28:09,397] Trial 6 finished with value: 0.8036064863204956 and parameters: {'n_estimators': 100, 'learning_rate': 0.04415748593834235, 'Algorithm__max_depth': 6, 'Algorithm__subsample': 0.9131252437193658}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:28:15,753] Trial 7 finished with value: 0.7992984056472778 and parameters: {'n_estimators': 100, 'learning_rate': 0.027920751799110397, 'Algorithm__max_depth': 7, 'Algorithm__subsample': 0.9087441542784761}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:28:21,232] Trial 8 finished with value: 0.8123703241348267 and parameters: {'n_estimators': 100, 'learning_rate': 0.0921946716415896, 'Algorithm__max_depth': 6, 'Algorithm__subsample': 0.9150164982279341}. Best is trial 2 with value: 0.8189159154891967.
[I 2026-07-20 15:28:28,228] Trial 9 finished with value: 0.819507384300232 and parameters: {'n_estimators': 100, 'learning_rate': 0.059764711553784856, 'Algorithm__max_depth': 8, 'Algorithm__subsample': 0.8867183739258785}. Best is trial 9 with value: 0.819507384300232.

In [87]:
study.best_params

{'n_estimators': 100,
 'learning_rate': 0.059764711553784856,
 'Algorithm__max_depth': 8,
 'Algorithm__subsample': 0.8867183739258785}

# final model

In [88]:
from sklearn.metrics import r2_score

In [89]:
# tuned hyperparameters from bayesian optimization 
xgb_model = Pipeline([('Data Preprocessing', Data_preprocessing),
                     ("Algorithm", XGBRegressor(
                         n_estimators=200,
                          learning_rate=0.05,
                          max_depth=8,
                           random_state=23))])


xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
r2score = r2_score(y_test,y_pred)
print("XGBoost")
print("Mean_Squared_Error:", mse)
print("Root_Mean_Squared_Error:", rmse)
print("R2_Score:",r2score)

XGBoost
Mean_Squared_Error: 15.704333305358887
Root_Mean_Squared_Error: 3.96286940574646
R2_Score: 0.8233687877655029

In [91]:
final_pipeline = xgb_model.fit(x, y)
final_pipeline

Pipeline(steps=[('Data Preprocessing',
                 ColumnTransformer(transformers=[('Nominal transformation',
                                                  Pipeline(steps=[('nominal '
                                                                   'imputation',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('Encoding',
                                                                   OneHotEncoder())]),
                                                  ['weather', 'type_of_order',
                                                   'type_of_vehicle',
                                                   'festival', 'city_name',
                                                   'order_day_of_week',
                                                   'order_time_of_day']),
                                                 ('Ordinal transformation',
                                                  Pipeline(s...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.05,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=8, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=200, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [92]:
import pandas as pd
test_data = [{
    'age': 25, 
    'ratings': 5.0, 
    'weather': 'cloudy', 
    'traffic': 'jam', 
    'vehicle_condition': 1, 
    'type_of_order': 'meal', 
    'type_of_vehicle': 'motorcycle', 
    'multiple_deliveries': 3, 
    'festival': 'no', 
    'city_type': 'urban', 
    'city_name': 'BANG', 
    'order_day': 13, 
    'order_month': 6, 
    'order_day_of_week': 'saturday', 
    'is_weekend': 1, 
    'pickup_time_minutes': 10,       
    'order_time_hour': 18, 
    'order_time_of_day': 'evening', 
    'distance': 5.5
}]

df_input = pd.DataFrame(test_data)

categorical_cols = [
    'weather', 'traffic', 'type_of_order', 'type_of_vehicle', 
    'festival', 'city_type', 'city_name', 'order_day_of_week', 'order_time_of_day'
]

for col in categorical_cols:
    df_input[col] = df_input[col].astype('category')

prediction = xgb.predict(df_input)

print(f"Predicted Delivery Time: {prediction[0]:.2f} minutes")

Predicted Delivery Time: 31.89 minutes

In [105]:
import pickle

In [106]:
with open(r"C:\swiggy\swiggy delivery time project.pkl","wb") as f:
    pickle.dump(final_pipeline,f)

In [107]:
import xgboost as xgb

In [108]:
xgb.__version__

'3.3.0'

In [109]:
!python --version

Python 3.13.5